name: wttr-weather # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: On the go weather update and weather check # 79 char long summary
description: |
  This is the CLI version of wttr.in with customizable options to it to limit the information being handed out.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  wttr-weather:
    source: https://github.com/GOSHROW/Weather-Script/archive/v1.0.tar.gz
    plugin: nil
